<?php

/**
 * @file
 * General hook implementations.
 */

/**
 * Implements hook_element_info().
 */
function islandora_authority_element_info() {
  global $base_url;
  $elements = array();

  $mod_path = drupal_get_path('module', 'islandora_authority');

  $elements['islandora_authority_textfield'] = array(
    '#theme' => 'islandora_authority_textfield',
    '#theme_wrappers' => array('form_element'),
    '#input' => TRUE,
    '#size' => 60,
    '#maxlength' => 128,
    '#autocomplete_path' => 'islandora/authority',
    '#process' => array(
      'ajax_process_form',
      'islandora_authority_load_theme_file',
      'islandora_authority_textfield_process',
      'islandora_authority_element_process',
    ),
    '#attached' => array(
      'library' => array(
        array('system', 'drupal.autocomplete'),
      ),
      'js' => array(
        "$mod_path/js/autocomplete.js",
        array(
          'type' => 'setting',
          'data' => array('baseUrl' => $base_url),
        ),
      ),
      'css' => array(
        "$mod_path/css/autocomplete.css",
      ),
    ),
  );
  $elements['islandora_authority_hidden'] = array(
    '#theme' => 'hidden',
    '#input' => TRUE,
    '#process' => array(
      'islandora_authority_load_theme_file',
      'islandora_authority_element_process',
    ),
  );

  return $elements;
}

/**
 * Implements hook_menu().
 */
function islandora_authority_menu() {
  $items = array();

  $items['islandora/authority'] = array(
    'page callback' => 'islandora_authority_autocomplete',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'includes/callback.inc',
  );
  $items['islandora/authority-validate'] = array(
    'page callback' => 'islandora_authority_validate',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'includes/callback.inc',
  );
  $items['admin/islandora/tools/islandora_authority'] = array(
    'title' => 'Islandora Authority',
    'description' => 'Configure the Islandora Authority module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_authority_admin_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/admin.form.inc',

  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function islandora_authority_theme() {
  $items = array();

  $items['islandora_authority_textfield'] = array(
    'render element' => 'element',
    'file' => 'theme/theme.inc',
  );

  return $items;
}

/**
 * Process so we can process.
 *
 * Drupal is silly and does not allow a file to be loaded reliably when loading
 * an element.
 */
function islandora_authority_load_theme_file($element, &$form_state, $complete_form) {
  form_load_include($form_state, 'inc', 'islandora_authority', 'theme/theme');
  return $element;
}
