<?php

/**
 * @file
 * General hook implementations.
 */

/**
 * Implements hook_element_info().
 */
function islandora_authority_element_info() {
  $elements = array();

  $mod_path = drupal_get_path('module', 'islandora_authority');

  $elements['islandora_authority_textfield'] = array(
    '#theme' => 'islandora_authority_textfield',
    '#theme_wrappers' => array('form_element'),
    '#input' => TRUE,
    '#size' => 60,
    '#maxlength' => 128,
    '#autocomplete_path' => 'islandora/authority',
    '#process' => array(
      'ajax_process_form',
      'islandora_authority_textfield_process',
      'islandora_authority_element_process',
    ),
    '#attached' => array(
      'library' => array(
        array('system', 'drupal.autocomplete'),
      ),
      'js' => array(
        "$mod_path/js/autocomplete.js",
      ),
      'css' => array(
        "$mod_path/css/autocomplete.css",
      ),
    ),
  );
  $elements['islandora_authority_hidden'] = array(
    '#theme' => 'hidden',
    '#input' => TRUE,
    '#process' => array(
      'islandora_authority_element_process',
    ),
  );

  return $elements;
}

/**
 * Implements hook_menu().
 */
function islandora_authority_menu() {
  $items = array();

  $items['islandora/authority'] = array(
    'page callback' => 'islandora_authority_autocomplete',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'includes/callback.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function islandora_authority_theme() {
  $items = array();

  $items['islandora_authority_textfield'] = array(
    'render element' => 'element',
    'file' => 'theme/theme.inc',
  );

  return $items;
}

/**
 * Process callback for islandora_authority elements.
 *
 * XXX: Would be in theme/theme.inc, but it doesn't appear to be loaded
 * reliably?
 */
function islandora_authority_element_process($element, &$form_state, $complete_form) {
  $element['#attributes']['id'] = implode('--', array(
    $complete_form['#build_id'],
    $element['#hash'],
  ));
  $form_state['cache'] = TRUE;
  return $element;
}

/**
 * Process callback for islandora_authority_textfield.
 *
 * XXX: Would be in theme/theme.inc, but it doesn't appear to be loaded
 * reliably?
 */
function islandora_authority_textfield_process($element, &$form_state, $complete_form) {
  $element['#autocomplete_path'] = implode('/', array(
    $element['#autocomplete_path'],
    $complete_form['#build_id'],
    $element['#hash'],
  ));
  return $element;
}
